version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/
  static_dir: static
- url: /polls/home/
  script: mysite.wsgi.application
  login: required
- url: /.*
  script: mysite.wsgi.application

libraries:
- name: django
  version: "1.5"

builtins:
- django_wsgi: on

env_variables:
 DJANGO_SETTINGS_MODULE: 'mysite.settings'
