# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-09 04:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_allotment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='picketpoint',
        ),
        migrations.RemoveField(
            model_name='picketpoint',
            name='event',
        ),
    ]
