# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-09 04:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_allotment', '0003_delete_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='PicketPoint',
        ),
    ]
