# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-09 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_allotment', '0010_delete_specialevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_place', models.CharField(max_length=200)),
                ('event_duration', models.CharField(max_length=200)),
                ('event_owner', models.CharField(max_length=200)),
            ],
        ),
    ]
