# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-10 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_allotment', '0011_policeevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=200)),
                ('p_code', models.CharField(max_length=200)),
                ('p_designation', models.CharField(max_length=200)),
                ('p_e_id', models.CharField(max_length=200)),
                ('p_pp_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EventPicketPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ep_name', models.CharField(max_length=200)),
            ],
        ),
    ]
