# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-10 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_allotment', '0012_eventparticipant_eventpicketpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventparticipant',
            name='p_e_id',
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='p_contact',
            field=models.CharField(default=9535365012, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='p_event_id',
            field=models.CharField(default=9535365012, max_length=200),
            preserve_default=False,
        ),
    ]
