# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-11 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_allotment', '0013_auto_20160610_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpicketpoint',
            name='ep_event_id',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
