# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-12 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_allotment', '0014_eventpicketpoint_ep_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policeevent',
            old_name='event_duration',
            new_name='event_end_date',
        ),
        migrations.AddField(
            model_name='policeevent',
            name='event_owner_branch',
            field=models.CharField(default='Pulivendula', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policeevent',
            name='event_owner_district',
            field=models.CharField(default='YSR Kadapa District', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policeevent',
            name='event_start_date',
            field=models.CharField(default='NOW', max_length=200),
            preserve_default=False,
        ),
    ]
