# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-20 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_allotment', '0016_eventparticipant_p_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventparticipant',
            old_name='p_gender',
            new_name='p_ps',
        ),
    ]
